version: '3.8'

services:
  prompt-chat:
    build: .
    container_name: prompt-chat
    ports:
      - "3000:80"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - prompt-network
networks:
  prompt-network:
    driver: bridge
